version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
  - cmd: net start MSSQL$SQL2019
configuration:
  - Release
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build . -v quiet
test_script:
  - cmd: dotnet test .
